name: kor_analyzer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/dictionary data/1_5000_20260319.json
    - assets/dictionary data/2_5000_20260319.json
    - assets/dictionary data/3_5000_20260319.json
    - assets/dictionary data/4_5000_20260319.json
    - assets/dictionary data/5_5000_20260319.json
    - assets/dictionary data/6_5000_20260319.json
    - assets/dictionary data/7_5000_20260319.json
    - assets/dictionary data/8_5000_20260319.json
    - assets/dictionary data/9_5000_20260319.json
    - assets/dictionary data/10_5000_20260319.json
    - assets/dictionary data/11_3439_20260319.json